package config

import (
	"bytes"
	"crypto/rand"
	"encoding/hex"
	"fmt"
)

// feedKeyBytes is the entropy behind a generated feed_api_key: 16 bytes renders
// as 32 hex characters, the shape the config comment has always recommended
// (`openssl rand -hex 16`) and twice the length the strength warning asks for.
const feedKeyBytes = 16

// SeedStarter returns the starter config with a freshly generated
// feed_api_key substituted for the example's empty one.
//
// The key gates the Torznab feed, whose /ab responses embed the operator's
// AnimeBytes passkey in every download link - so it protects a tracker
// credential. It is also the ONE credential in this config the operator invents
// rather than copies (the Prowlarr key and the AB passkey are generated by those
// services at a fixed length), which is exactly why it was the one that could be
// weak. Generating it here removes that possibility at the only moment the app
// authors this file, instead of trying to measure it afterwards: a length rule
// would reject a sound short random key and accept a long guessable phrase, and
// the genuinely guessable value - the unexpanded ${VAR} placeholder, readable
// from the public README - already fails config validation outright.
//
// Deliberately scoped to the starter write and nowhere else. An empty key on a
// configured feed stays the hard validation error it is: this app reads its
// config once and never rewrites it, so silently filling a field in a file the
// operator is already running would be a surprise, and a key that appeared
// without them seeing it could not be pasted into Sonarr.
//
// The committed config.example.yaml keeps its empty value, so no key is ever
// published; the substitution happens only in the bytes written to disk. The
// embed and the atomic write stay in the composition root (embed cannot reach a
// parent directory, and the example ships at the repo root for users); this
// package owns the config file's vocabulary, which is what the substitution is
// anchored on.
func SeedStarter(example []byte) ([]byte, error) {
	buf := make([]byte, feedKeyBytes)
	if _, err := rand.Read(buf); err != nil {
		return nil, fmt.Errorf("generate feed_api_key for the starter config: %w", err)
	}
	// Anchored on the example's exact empty-value spelling and applied once, so
	// a future edit that changes that line fails the starter test rather than
	// silently writing an unkeyed config.
	const placeholder = `feed_api_key: ""`
	replacement := fmt.Sprintf("feed_api_key: %q", hex.EncodeToString(buf))
	seeded := bytes.Replace(example, []byte(placeholder), []byte(replacement), 1)
	if bytes.Equal(seeded, example) {
		return nil, fmt.Errorf("starter config no longer contains %s; cannot seed a feed_api_key", placeholder)
	}
	return seeded, nil
}
